from math import floor

TOTAL_EPISODES = 100
WORKER_EPISODE_COUNT = floor(TOTAL_EPISODES * 0.40)
MERGED_EPISODE_COUNT = TOTAL_EPISODES - WORKER_EPISODE_COUNT
SEED = 1
EXCHANGE_INFO = True
GRID_WIDTH = 10
GRID_HEIGHT = 10
AGENT_COUNT = 2
FOOD_COUNT = 10
OBSTACLE_COUNT = (GRID_WIDTH * GRID_HEIGHT) // 10
NEST_COUNT = 1
AGENT_VISION_RADIUS = 0
CARRY_CAPACITY = 1
WORKER_COUNT = 2


EPSILON_DECAY_RATE = 1 / (WORKER_EPISODE_COUNT + MERGED_EPISODE_COUNT)
EPSILON_MIN = 0.001
LEARNING_RATE_ALPHA = 0.50
DISCOUNT_FACTOR_GAMMA = 0.90
ACTION_COUNT = 4


SQUARE_PIXEL_WIDTH = 40
EPISODE_AVERAGE_STEP = 1
DRAW_ARROWS = True
SHOW_AFTER_TRAINING = True
SAVE_AFTER_TRAINING = False