# Training params
EPISODES = 100_000
SEED = 0
AGENTS_EXCHANGE_INFO = True
GRID_WIDTH = 20
GRID_HEIGHT = 20
AGENT_COUNT = 2
FOOD_COUNT = 5
OBSTACLE_COUNT = 20
NEST_COUNT = 1
AGENT_VISION_RADIUS = 0
CARRY_CAPACITY = 1
EPSILON_START = 1.00
EPSILON_DECAY_RATE = EPSILON_START / (EPISODES / 2)
EPSILON_MIN = 0.01
LEARNING_RATE_ALPHA = 0.50
MAX_STEPS = 50_000
DISCOUNT_FACTOR_GAMMA = 0.90
LEARNING_METHOD = "Q" # Q, Sarsa

# Visualization params
SQUARE_PIXEL_WIDTH = 40
RENDER_FPS = 30
SECONDS_BETWEEN_AUTO_STEP = 0.10
ACTION_COUNT = 4
GRAPH_STEP = 1000 # Change to average
DRAW_ARROWS = True
SHOW_AFTER_TRAINING = True

# Saving params
SAVE_AFTER_TRAINING = True
SAVE_DIRECTORY = "../runs/"
FILE_NAME = (
    f"M={LEARNING_METHOD} "
    f"E={EPISODES} "
    f"S={SEED} "
    f"GW={GRID_WIDTH} "
    f"GH={GRID_HEIGHT} "
    f"AC={AGENT_COUNT} "
    f"FC={FOOD_COUNT} "
    f"NC={NEST_COUNT} "
    f"OC={OBSTACLE_COUNT} "
    f"AVR={AGENT_VISION_RADIUS} "
    f"AEI={AGENTS_EXCHANGE_INFO} "
    f"CC={CARRY_CAPACITY} "
    f"MS={MAX_STEPS}"
)